---
title: 'Lecture 3: Computer Representation of Numbers'
author: "Tyler J. Brough"
date: "January 16, 2017"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

## Finance 6320: Computational Finance

#### January 17, 2017

<br>

Today's Agenda:

1. Review of installations, setup, etc. Also questions?
2. Computer Representation of Numbers
3. Algorithms

## Installation, Setup, Etc

<br>
<br>

Questions?


## Computer Representation of Numbers

<br>

It is crucial to understand that computers __DO NOT__ represent numbers the same way that we do as humans. 

<br>

The Word _digital_ in digital computer means that computers use binary digits, that is 0's and 1's to represent numbers. This is also known as base 2 representation.


## Two Guiding Principles

Throughout the course we will repeat two guiding principles:

<br>

1. _Computer numbers are not the same as real numbers, and the arithmetic operations on computer numbers are not exactly the same as those of ordinary arithmetic._

<br>

2. _The form of a mathematical expression and the way the expression should be evaluated in actual practice may be quite different._

<br>

Reference: [Gentle](https://goo.gl/knKqZ7)


## Computer Representation of Numbers

### Numbers in Base 10

In the familiar decimal (base 10) system, numerical values are represented in units or powers of 10. 

<br>

Now we can use the ___Basic Representation Theorem___, which says we can represent a number, $k$, as

$$
k = \sum\limits_{j=0}^{m} a_{j} (10)^{j}
$$

for some unique integer $m$ and some set of integer coefficients ${a_{0}, \ldots, a_{m}}$.


## An Example

As an example, consider the following:

$$
193 = 1 \ast (10)^{2} + 9 \ast (10)^{1} + 3 \ast (10)^0
$$

where * indicates multiplication. So in this case:

* $m = 2$
* $a_{0} = 3$
* $a_{1} = 9$
* $a_{2} = 1$

NB: it is necessarily the case that $0 \le a_{j} \le 9$.


## 

Since transitors on computers have only two states, a computer represents a number in base 2.

<br>

The binary version of the above becomes:

$$
k = \sum\limits_{j=0}^{m} b_{j} (2)^{j}
$$

where $m$ is a non-negative integer for which $b_{m} \ne 0$. The $b_{j}$'s are coefficients that can take only the values 0 and 1.


##

Returning to our example:

$$
\begin{align}
193 &= 1 \ast (2)^{7} + 1 \ast (2)^{6} + 1 \ast (2)^{0} \\
    &= 128 \quad + \quad 64 \quad +  \quad 1 \\
\end{align}
$$

This corresponds to:

* $m = 7$
* $b_{7} = b_{6} = b_{0} = 1$
* $b_{5} = \cdots = b_{1} = 0$


##

We can represent this in a tabular representation as follows:

------------  -----  -----  -----  -----  -----  -----  ------ -----
Power of two  $2^7$  $2^6$  $2^5$  $2^4$  $2^3$  $2^2$  $2^1$  $2^0$
Coefficient   1      1      0      0      0      0      0      1
------------  -----  -----  -----  -----  -----  -----  -----  -----

<br>

That is, the nuber 193 in base 10 can represented in exactly one byte (8 bits) as: 11000001

<br>

_NB:_ a bit is a _binary digit_


##

Binary arithmetic works by associating machine memory bits and bytes with individual transistors and blocks of eight transistors.

<br>

To represent a given number in memory its binary representation is physically created by allocating a block of memory, indentifying the individual transistors in the block with a power of two


##

Just as 193 cannot be stored in exactly 7 bits, there is a liimit to the size of numbers that can be stored in any finite number of bits

<br>

For exampe, the largest number that can be stored in one byte is:

$$
\sum\limits_{j=0}^{7}(2)^{j} = 2^{7} \sum\limits_{j=0}^{7} (2)^{-j} = 2^{7} \frac{1 - (1/2)^{8}}{1 - (1/2)} = 2^{8} - 1 = 255
$$

<br>

More generally, the largest number that can be stored in $m$ bits is $2^{m} - 1$


## Floating-Point Numbers

This is an important topic, but we can't spend too much time. 

<br>

Please see the following:

1. The [wikipedia article](https://en.wikipedia.org/wiki/Floating_point)

2. This [article](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)


## Errors

It is important to understand the kinds of errors that can occur with floating-point numbers

* Buffer overflow
* Buffer underflow
* Others

